export const FETCH_SUCCESS = 'DETAIL_FETCH_SUCCESS';
export const FETCH_FAILURE = 'DETAIL_FETCH_FAILURE';
export const CLEAR_DATA = 'DETAIL_CLEAR_DATA';
export const CREATE_SUCCESS = 'DETAIL_CREATE_SUCCESS';
export const CREATE_FAILURE = 'DETAIL_CREATE_SUCCESS';
export const FETCH_CHILD_SUCCESS = 'DETAIL_FETCH_CHILD_SUCCESS';
