export const FETCH = 'DETAIL_FETCH';
export const FETCH_SUCCESS = 'DETAIL_FETCH_SUCCESS';
export const FETCH_FAILURE = 'DETAIL_FETCH_FAILURE';
export const FETCH_CANCELLED = 'DETAIL_FETCH_CANCELLED';
export const CLEAR_DATA = 'DETAIL_CLEAR_DATA';
export const DELETE_SUCCESS = 'DETAIL_DELETE_SUCCESS';
export const DELETE_FAILURE = 'DETAIL_DELETE_FAILURE';
export const UPDATE_FAILURE = 'DETAIL_UPDATE_FAILURE';
