export const EXECUTE = 'CUSTOM_ACTION_EXECUTE';
export const EXECUTE_SUCCESS = 'CUSTOM_ACTION_EXECUTE_SUCCESS';
export const EXECUTE_FAILURE = 'CUSTOM_ACTION_EXECUTE_FAILURE';
export const CLEAR_RESPONSE = 'CUSTOM_ACTION_CLEAR_RESPONSE';
