export const FETCH = 'TABLE_FETCH';
export const FETCH_SUCCESS = 'TABLE_FETCH_SUCCESS';
export const FETCH_FAILURE = 'TABLE_FETCH_FAILURE';
export const FETCH_CANCELLED = 'TABLE_FETCH_CANCELLED';

export const CLEAR_DATA = 'TABLE_CLEAR_DATA';

export const CREATE = 'TABLE_CREATE';
export const CREATE_SUCCESS = 'TABLE_CREATE_SUCCESS';
export const CREATE_FAILURE = 'TABLE_CREATE_FAILURE';

export const PURGE = 'TABLE_PURGE';
export const PURGE_SUCCESS = 'TABLE_PURGE_SUCCESS';
export const PURGE_FAILURE = 'TABLE_PURGE_FAILURE';

export const UPDATE = 'TABLE_UPDATE';
export const UPDATE_SUCCESS = 'TABLE_UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'TABLE_UPDATE_FAILURE';
