export const OPEN = 'DIALOG_OPEN';
export const CLOSE = 'DIALOG_CLOSE';
export const PREPARE_SUCCESS = 'DIALOG_PREPARE_SUCCESS';
export const PREPARE_FAILURE = 'DIALOG_PREPARE_FAILURE';
export const ERROR = 'DIALOG_ERROR';
export const CLEAR_ERROR = 'DIALOG_CLEAR_ERROR';
export const CLEAR_DATA = 'DIALOG_CLEAR_DATA';
