export const FETCH_SUCCESS = 'TABLE_FETCH_SUCCESS';
export const FETCH_FAILURE = 'TABLE_FETCH_FAILURE';
export const CLEAR_DATA = 'TABLE_CLEAR_DATA';
export const CREATE_SUCCESS = 'TABLE_CREATE_SUCCESS';
export const CREATE_FAILURE = 'TABLE_CREATE_SUCCESS';
