#!/bin/sh

# Check JavaScript code style
RUN_JSCS=1
RUN_TESTS=1
TOTAL_ERRORS=0
JSCS_PATH=`command -v ./node_modules/.bin/eslint`
JSFILES=$(git diff-index --name-status --cached HEAD | grep -v ^D | grep -oP '^((?!karma|test|node_modules|bower_components|webpack).)*$' | egrep '.js$' | cut -c3-)
if [ -z "$JSFILES" ]; then
    # No JavaScript file changed for this commit
    echo "Files not changed"
    RUN_JSCS=0
    RUN_TESTS=0
elif [ -z "$JSCS_PATH" ]; then
    echo "Warning: You can't check the JS coding style."
    echo "You need to download and install jscs and set JSCS_PATH to its path."
    RUN_JSCS=0
fi

# Ensuring proper coding style
if [ $RUN_JSCS -ne 0 ]; then
    echo -n "Checking JS style errors..."
    echo $JSFILES
    OUT=`$JSCS_PATH -c ./.eslintrc $JSFILES`
    CODE=$?
    # Erase last output line
    echo -ne '\r\033[K'
    if [ $CODE -ne 0 ]; then
        echo "\033[1;31mJavaScript style errors found:\033[0m"
        echo "$OUT"

        echo "Please fix and stage the files before commiting again."
        exit $CODE
    else
        echo "\033[1;32mNo JS code style errors found."
    fi
fi

# Running tests
NPM_TESTCMD="npm run test"

if [ $RUN_TESTS -ne 0 ]; then
  echo "Running tests..."
  $NPM_TESTCMD
  CODE=$?

  exit $CODE
fi
