export const FETCH_SUCCESS = 'DYNAMIC_FETCH_SUCCESS';
export const FETCH_FAILURE = 'DYNAMIC_FETCH_FAILURE';
export const CLEAR_DATA = 'DYNAMIC_CLEAR_DATA';
export const CREATE_SUCCESS = 'DYNAMIC_CREATE_SUCCESS';
export const CREATE_FAILURE = 'DYNAMIC_CREATE_SUCCESS';
export const FETCH_CHILD_SUCCESS = 'DYNAMIC_FETCH_CHILD_SUCCESS';
