export const LOGOUT = 'AUTH_LOGOUT';
export const LOGIN_INPROGRESS = 'AUTH_LOGIN_INPROGRESS';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const TENANT_FETCH_SUCCESS = 'AUTH_TENANT_FETCH_SUCCESS';
export const TENANT_FETCH_FAILURE = 'AUTH_TENANT_FETCH_FAILURE';
export const CLEAR_STORAGE = 'AUTH_CLEAR_STORAGE';
