export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const TENANT_FETCH = 'TENANT_FETCH';
export const TENANT_FETCH_SUCCESS = 'TENANT_FETCH_SUCCESS';
export const TENANT_FETCH_FAILURE = 'TENANT_FETCH_FAILURE';
