export const LOGOUT = 'AUTH_LOGOUT';
export const LOGIN_INPROGRESS = 'AUTH_LOGIN_INPROGRESS';
export const LOGIN = 'AUTH_LOGIN';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const FETCH_TENANTS = 'AUTH_FETCH_TENANTS';
export const FETCH_TENANTS_SUCCESS = 'AUTH_FETCH_TENANTS_SUCCESS';
export const FETCH_TENANTS_FAILURE = 'AUTH_FETCH_TENANTS_FAILURE';

export const SELECT_TENANT = 'AUTH_SELECT_TENANT';
export const SELECT_TENANT_SUCCESS = 'AUTH_SELECT_TENANT_SUCCESS';
export const SELECT_TENANT_FAILURE = 'AUTH_SELECT_TENANT_FAILURE';

export const SHOW_TOKEN_RENEWAL = 'AUTH_SHOW_TOKEN_RENEWAL';
export const RENEW_TOKEN = 'AUTH_RENEW_TOKEN';
export const RENEW_TOKEN_SUCCESS = 'AUTH_RENEW_TOKEN_SUCCESS';
export const RENEW_TOKEN_FAILURE = 'AUTH_RENEW_TOKEN_FAILURE';

export const CLEAR_STORAGE = 'AUTH_CLEAR_STORAGE';
