name: PR check
on:
  push:
    paths:
    - '*.js'
    - '*.jsx'
    - '*.ts'
    - '*.tsx'
    - '*.scss'
    - '*.less'
    - '*.json'
  pull_request:
    paths:
    - '*.js'
    - '*.jsx'
    - '*.ts'
    - '*.tsx'
    - '*.scss'
    - '*.less'
    - '*.json'
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and run tests
      run: |
        npm install
        npm run test-cover
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and run lint
      run: |
        npm install
        npm run lint
  build:
    name: Run build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and run build
      run: |
        npm install
        npm run build
